# Exported from Render on 2025-10-29T18:54:33Z
version: "1"
services:
- type: web
  name: timeshift
  runtime: python
  repo: https://github.com/coolrich/timeshift
  plan: free
  envVars:
  - key: DATABASE_URL
    sync: false
  - key: EMAIL
    sync: false
  - key: PASSWORD
    sync: false
  - key: USERNAME
    sync: false
  - key: SECRET_KEY
    sync: false
  - key: SITE_NAME
    sync: false
  - fromGroup: TimeShift
  region: oregon
  buildCommand: >
    pip install -r requirements.txt &&
    python manage.py migrate &&
    python manage.py collectstatic --noinput &&
    python post_deploy.py
  startCommand: gunicorn django_project.wsgi:application --bind 0.0.0.0:$PORT
  autoDeployTrigger: commit
