# Generated by Django 5.2.5 on 2025-08-20 09:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSimulationState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=64, unique=True)),
                ('simulated_time', models.DateTimeField(blank=True, null=True)),
                ('simulation_start_time', models.DateTimeField(blank=True, null=True)),
                ('tick_enabled', models.BooleanField(default=False)),
                ('registered_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_state', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
