# Generated by Django 5.2.5 on 2025-12-10 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='virtualclock',
            name='api_token',
        ),
    ]
