# Generated by Django 5.2.5 on 2025-11-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualclock',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='virtualclock',
            name='private_id',
        ),
        migrations.AlterField(
            model_name='virtualclock',
            name='id',
            field=models.PositiveIntegerField(default=1, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
