# Generated by Django 5.2.5 on 2026-01-02 15:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_virtualclock_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='virtualclock',
            name='speed',
            field=models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(100.0)]),
        ),
    ]
