# Generated by Django 5.2.5 on 2025-11-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_virtualclock_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualclock',
            name='id',
            field=models.PositiveIntegerField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
