# Generated by Django 5.2.5 on 2025-08-21 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_usersimulationstate_simulationstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='simulationstate',
            old_name='registered_at',
            new_name='created_at',
        ),
    ]
