# Generated by Django 6.0.1 on 2026-02-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_virtualclock_speed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualclock',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
