# Generated by Django 5.2.5 on 2025-08-21 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_registered_at_to_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulationstate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='simulationstate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
