# Generated by Django 5.2.5 on 2025-08-21 10:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_simulationstate_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulationstate',
            name='simulated_time',
        ),
        migrations.RemoveField(
            model_name='simulationstate',
            name='simulation_start_time',
        ),
        migrations.AddField(
            model_name='simulationstate',
            name='current_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='simulationstate',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='simulationstate',
            name='api_token',
            field=models.CharField(editable=False, max_length=64, unique=True),
        ),
    ]
