# Generated by Django 5.2.5 on 2025-08-22 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_virtualclock_id_alter_virtualclock_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualclock',
            options={'ordering': ['public_id']},
        ),
        migrations.AddField(
            model_name='virtualclock',
            name='public_id',
            field=models.PositiveIntegerField(default=1, editable=False, unique=True),
        ),
    ]
