# Generated by Django 5.2.5 on 2025-08-25 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_virtualclock_options_virtualclock_public_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='virtualclock',
            old_name='user',
            new_name='user_owner',
        ),
        migrations.AddField(
            model_name='virtualclock',
            name='allowed_users',
            field=models.ManyToManyField(blank=True, related_name='shared_clocks', to=settings.AUTH_USER_MODEL),
        ),
    ]
