# Generated by Django 5.2.5 on 2025-09-28 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_user_virtualclock_user_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='virtualclock',
            options={'ordering': ['private_id']},
        ),
        migrations.RenameField(
            model_name='virtualclock',
            old_name='public_id',
            new_name='private_id',
        ),
    ]
