# Generated by Django 5.2.5 on 2025-09-28 08:37

import uuid

from django.db import migrations, models


def gen_tokens(apps, schema_editor):
    User = apps.get_model('accounts', 'TimeShiftUser')
    for user in User.objects.all():
        if not user.user_api_token:
            user.user_api_token = uuid.uuid4()
            user.save(update_fields=['user_api_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeshiftuser',
            name='user_api_token',
            field=models.UUIDField(editable=False, null=True, blank=True),
        ),
        migrations.RunPython(gen_tokens, reverse_code=migrations.RunPython.noop),
    ]
