# Generated by Django 5.2.5 on 2025-09-28 08:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_timeshiftuser_user_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeshiftuser',
            name='user_api_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
