# Generated by Django 5.2.5 on 2025-09-28 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_timeshiftuser_user_api_token'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeshiftuser',
            old_name='user_api_token',
            new_name='api_token',
        ),
    ]
