# Generated by Django 5.2.5 on 2025-11-01 19:25

from django.db import migrations, models

import accounts


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_user_api_token_timeshiftuser_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeshiftuser',
            name='api_token',
            field=models.CharField(default=accounts.models.user.generate_api_token, editable=False, max_length=64, unique=True),
        ),
    ]
