# Generated by Django 5.2.5 on 2025-11-04 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_timeshiftuser_api_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeshiftuser',
            name='api_token',
            field=models.CharField(default='', editable=False, max_length=64, unique=True),
        ),
    ]
