# Generated by Django 5.2.5 on 2025-11-19 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_timeshiftuser_api_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeshiftuser',
            name='max_clocks_count',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
