# Generated by Django 5.2.5 on 2025-11-19 13:26

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_timeshiftuser_max_clocks_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeshiftuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
