# Generated by Django 5.2.5 on 2025-11-19 13:30

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_timeshiftuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeshiftuser',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
