# Generated by Django 5.2.5 on 2025-11-23 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_timeshiftuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeshiftuser',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Часова зона користувача, наприклад Europe/Kyiv', max_length=50),
        ),
    ]
