# Generated by Django 5.2.5 on 2025-12-15 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_timeshiftuser_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeshiftuser',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.MinLengthValidator(3)]),
        ),
    ]
