# Generated by Django 5.2.5 on 2025-12-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_timeshiftuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeshiftuser',
            name='token_last_refreshed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
