# Generated by Django 5.2.5 on 2025-12-17 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_timeshiftuser_token_last_refreshed_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timeshiftuser',
            old_name='api_token',
            new_name='_api_token',
        ),
        migrations.RenameField(
            model_name='timeshiftuser',
            old_name='token_last_refreshed_at',
            new_name='_token_last_refreshed_at',
        ),
    ]
