# Generated by Django 5.2.5 on 2026-01-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_rename_api_token_timeshiftuser__api_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeshiftuser',
            name='max_clocks_count',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
