# Generated by Django 6.0.1 on 2026-03-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_throttlerule_scope'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeshiftuser',
            name='clock_create_rate',
            field=models.CharField(default='5/min', max_length=32),
        ),
    ]
