# Generated by Django 6.0.1 on 2026-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_timeshiftuser_clock_create_rate'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='throttlerule',
            name='requests_must_be_positive',
        ),
        migrations.RenameField(
            model_name='throttlerule',
            old_name='requests',
            new_name='requests_count',
        ),
        migrations.RemoveField(
            model_name='timeshiftuser',
            name='clock_create_rate',
        ),
        migrations.AddField(
            model_name='timeshiftuser',
            name='period',
            field=models.CharField(choices=[('s', 'Second'), ('m', 'Minute'), ('h', 'Hour'), ('d', 'Day')], default='m', max_length=1),
        ),
        migrations.AddField(
            model_name='timeshiftuser',
            name='requests_count',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AddConstraint(
            model_name='throttlerule',
            constraint=models.CheckConstraint(condition=models.Q(('requests_count__gt', 0)), name='requests_must_be_positive'),
        ),
    ]
