# Generated by Django 6.0.1 on 2026-03-24 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_throttlerule_requests_must_be_positive_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='throttlerule',
            old_name='requests_count',
            new_name='max_requests',
        ),
        migrations.RenameField(
            model_name='timeshiftuser',
            old_name='requests_count',
            new_name='max_requests',
        ),
    ]
