# Generated by Django 6.0.1 on 2026-03-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_rename_requests_count_throttlerule_max_requests_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersubscription',
            options={'verbose_name': 'Підписка', 'verbose_name_plural': 'Підписки'},
        ),
        migrations.RemoveConstraint(
            model_name='throttlerule',
            name='requests_must_be_positive',
        ),
        migrations.AlterField(
            model_name='throttlerule',
            name='max_requests',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='throttlerule',
            name='period',
            field=models.CharField(choices=[('s', 'Second'), ('m', 'Minute'), ('h', 'Hour'), ('d', 'Day')], default='m', max_length=1),
        ),
        migrations.AlterField(
            model_name='throttlerule',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('clock_create', 'Clock Create')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='throttlerule',
            constraint=models.CheckConstraint(condition=models.Q(('max_requests__gt', 0)), name='requests_must_be_positive'),
        ),
        migrations.AddConstraint(
            model_name='usersubscription',
            constraint=models.UniqueConstraint(fields=('user',), name='unique_user_subscription'),
        ),
    ]
