# Generated by Django 6.0.1 on 2026-04-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_usersubscription_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeshiftuser',
            name='max_requests',
        ),
        migrations.RemoveField(
            model_name='timeshiftuser',
            name='period',
        ),
        migrations.AddField(
            model_name='timeshiftuser',
            name='rates',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='timeshiftuser',
            name='rates_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='throttlerule',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('clock_create', 'Clock Create')], default='global', max_length=20),
        ),
    ]
