# Generated by Django 6.0.1 on 2026-05-31 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_remove_timeshiftuser_max_requests_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='throttlerule',
            name='scope',
            field=models.CharField(choices=[('global', 'Global'), ('clock_create', 'Clock Create'), ('token_refresh', 'Token Refresh'), ('clock_control', 'Clock Control'), ('profile_settings', 'Profile Settings'), ('clock_delete', 'Clock Delete')], default='global', max_length=20),
        ),
    ]
